[package]
name = "curiouswolf"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.8.0", features = ["web-axum"] }
shuttle-shared-db = { version = "0.8.0", features = ["postgres", "sqlx"] }
axum = "0.6.2"
sync_wrapper = "0.1.1"
askama = { version = "0.11.1", features = ["with-axum"] }
askama_axum = "0.2.1"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres"] }
