CREATE TABLE push_subscriptions (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id),
    endpoint VARCHAR(512) UNIQUE NOT NULL,
    p256dh VARCHAR(512) UNIQUE NOT NULL,
    auth VARCHAR(512) UNIQUE NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);