CREATE TABLE users (
    id SERIAL PRIMARY KEY NOT NULL,
    uuid UUID UNIQUE NOT NULL,
    username VARCHAR(15) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE questions (
    id SERIAL PRIMARY KEY NOT NULL,
    body TEXT NOT NULL,
    recipient_id INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE answers (
    id SERIAL PRIMARY KEY NOT NULL,
    body TEXT NOT NULL,
    question_id INTEGER NOT NULL REFERENCES questions(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE credentials (
    id SERIAL PRIMARY KEY NOT NULL,
    user_uuid UUID NOT NULL REFERENCES users(uuid),
    passkey JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);